function getData() {

    try {
        console.log(userInfoData);
    } catch(err) {
        console.log("Exception Occurred During Execution")
    }
    
    console.log("Execution Done...")
}

getData();